# Generated by Django 5.2.6 on 2025-11-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="account_locked_until",
        ),
        migrations.RemoveField(
            model_name="user",
            name="failed_login_attempts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_ip",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
