# Generated by Django 5.2.6 on 2025-11-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0002_update_user_model_username"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailverification",
            name="auth_email__token_bf7334_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailverification",
            name="auth_email__user_id_9be1b6_idx",
        ),
        migrations.RemoveIndex(
            model_name="magiclink",
            name="auth_magic__token_4b286a_idx",
        ),
        migrations.RemoveIndex(
            model_name="magiclink",
            name="auth_magic__email_50742a_idx",
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["token", "is_verified"], name="auth_email__token_b15b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["user", "is_verified", "expires_at"],
                name="auth_email__user_id_df762c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["email", "is_verified"], name="auth_email__email_c1977c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="magiclink",
            index=models.Index(
                fields=["token", "is_used"], name="auth_magic__token_fe58f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="magiclink",
            index=models.Index(
                fields=["email", "expires_at"], name="auth_magic__email_7de938_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="magiclink",
            index=models.Index(
                fields=["created_at"], name="auth_magic__created_19ba0e_idx"
            ),
        ),
    ]
