# Generated by Django 5.2.6 on 2025-11-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0004_alter_extracteddata_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extracteddata",
            name="currency",
            field=models.CharField(
                blank=True,
                default="USD",
                help_text="Currency code (ISO 4217)",
                max_length=3,
                null=True,
            ),
        ),
    ]
