# Generated by Django 5.2.6 on 2025-11-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_service", "0003_remove_ledgerentry_ai_confidence_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="file_path",
            field=models.CharField(
                help_text="Relative path to file in storage backend", max_length=500
            ),
        ),
    ]
